### ISSUE TITLE
add support for tags

### ISSUE THREAD

**Issue by bengreenier** [unwitting/twine-parser#1]
Hello! Using this for an alexa skill and it's working great (huge thank you! 👍 ) - i'm creating this to track adding support for tags - what i'd like to do is parse tags as well into the `passage` object such that I can use them to more clearly indicate story completion (success or failure).

Let me know your thoughts - My plan is to submit this feature as a PR sometime soon. 🚀

**Comment by bengreenier** [comment]
actually, sounds like @benferse was taking a stab at this - Any updates, Ben?

**Comment by unwitting** [comment]
Awesome, always nice to find out someone's getting some use out of a hobby project! No problem with the concept, this is probably only missing because I wasn't all that famililar with the structure / capabilities of Twine games when I wrote this. Look forward to the PR.

**Comment by benferse** [comment]
Yup - I put this together this weekend. I can send a PR in the next day or so, I'm just searching for example story files to validate the format (the spec that I have isn't super clear about what's legit in a tag)

**Comment by bengreenier** [comment]
closed with #2
